95 create signin api
harakeke-2019/EDAMAME pull request #129
Opened 2019-02-25 22:01 UTC by rebeccazhangnz

created client side auth api
closes #95

2019-02-25 22:43 UTC, emilyparkes requested changes

2019-02-25 22:43 UTC, emilyparkes commented on client/api/auth.js
> +const url = 'http://localhost:3000'
Please put the api here `const url = 'http://localhost:3000/api/v1/auth` as any other routes for this api will use the same url.

2019-02-25 22:43 UTC, emilyparkes commented on client/api/auth.js
> +    .post(`${url}/api/v1/auth/signin`)
this will be `${url}/signin`

2019-02-25 22:47 UTC, rebeccazhangnz commented on client/api/auth.js
> +    .post(`${url}/api/v1/auth/signin`)
changes has been made. Thanks.

2019-02-26 01:18 UTC, emilyparkes approved these changes

2019-02-26 01:19 UTC, merged