Progress modules to dashboard 60
harakeke-2019/EDAMAME pull request #64
Opened 2019-02-22 00:46 UTC by lanelps

closes #60

2019-02-22 01:35 UTC, emilyparkes requested changes

2019-02-22 01:35 UTC, emilyparkes commented on client/components/Dashboard.jsx
> +    tally: 20
could this be changed to percentage? Tally doesn't quite make sense in this context.

2019-02-22 01:35 UTC, emilyparkes commented on client/components/ProgressModule.jsx
> +  const percentage = props.placeHolderProps.tally
Again here. Why is it tally and then named to percentage?

2019-02-24 21:33 UTC, emilyparkes approved these changes

2019-02-24 21:33 UTC, merged

2019-02-24 22:04 UTC, chrislaupama commented
@lanelps this isn't working on my end.

https://github.com/harakeke-2019/EDAMAME/commit/cf2f5edcbc08d3371999048ad7fe70e10d0eeaf2

`import CircularProgressbar from 'react-circular-progressbar'`

2019-02-24 22:09 UTC, chrislaupama commented
@lanelps I'm having an issue with https://github.com/harakeke-2019/EDAMAME/commit/cf2f5edcbc08d3371999048ad7fe70e10d0eeaf2 running.

It looks like `import CircularProgressbar from 'react-circular-progressbar'` isn't importing anything.