Connect register route and add bcrypt auth mahi
harakeke-2019/EDAMAME pull request #72
Opened 2019-02-22 02:08 UTC by nzbenji

closes #36 
Kia ora we need this to progress with connecting to the registration form. 

thanks :)

2019-02-22 02:56 UTC, chrislaupama submitted a review, later dismissed
Awesome work team!

2019-02-22 03:06 UTC, nzbenji commented
Kia ora @chrislaupama we have pushed up more stuff for review. Thanks!

2019-02-24 21:41 UTC, emilyparkes requested changes

2019-02-24 21:41 UTC, emilyparkes commented on package.json
> +    "dev": "nodemon server & webpack --watch",
Please remove this change as it is irrelevant to your ticket. If this change is needed create a new ticket please.

2019-02-24 21:41 UTC, emilyparkes commented on server/routes/starter.js
> +// const db = require('../../db')
Why was this change made?

2019-02-24 21:41 UTC, emilyparkes commented on server/server.js
> +const auth = require('./routes/auth')
Please follow code style of `const authRoutes = require('./routes/auth')`

2019-02-24 21:41 UTC, emilyparkes commented on server/server.js
> +server.use('/api/v1/auth/register', auth)
Please follow code style of `server.use('/api/v1/auth/register', authRoutes)`

2019-02-24 23:10 UTC, closed without merging

2019-02-24 23:10 UTC, nzbenji commented
Closed without merging because we will no longer use bcrypt for authentication