36 register route
harakeke-2019/EDAMAME pull request #85
Opened 2019-02-24 23:51 UTC by nzbenji

Changed method for authentication.
Now using Don's suggested way with libsodium , jsonwebtoken and dotenv.

Register route now returns a unique token for user if user.name and user.surename does not exist in the database.

closes #36

2019-02-24 23:52 UTC, nzbenji commented
The wiki needs to be updated.

2019-02-25 01:02 UTC, emilyparkes commented
@nzbenji can you please update the wiki then :)

2019-02-25 01:03 UTC, emilyparkes requested changes

2019-02-25 01:03 UTC, emilyparkes commented on server/server.js
> +const auth = require('./routes/auth')
Please follow code convention of `const authRoutes = require('./routes/auth')`

2019-02-25 01:03 UTC, emilyparkes commented on server/server.js
> +server.use('/api/v1/auth', auth)
Please follow code convention of `server.use('/api/v1/auth', authRoutes)`

2019-02-25 01:05 UTC, emilyparkes requested changes

2019-02-25 01:05 UTC, emilyparkes commented on server/db/users.js
> +const environment = process.env.NODE_ENV || 'development'
Please use what you removed in line 1 as the next few lines are from the index file it imports.

2019-02-25 01:59 UTC, nzbenji commented
Made amendments to files

2019-02-25 02:14 UTC, emilyparkes submitted a review, later dismissed

2019-02-25 03:56 UTC, emilyparkes approved these changes

2019-02-25 04:25 UTC, merged